Cypress updated, test scripts fixed
Katona/really-simple-xdm pull request #27
Opened 2022-10-13 15:33 UTC by gsanta

I updated cypress to the latest version and changed some of the package.json scripts to be able to run cypress tests locally (that part was either incomplete before or I just could not figure out how to run them) 

Also modified circleci script to run the tests with the "new way"

2022-10-19 12:29 UTC, Katona requested changes
Thanks for the PR :) I had one minor comment.

2022-10-19 12:29 UTC, Katona commented on package.json
> +    "cypress": "^10.10.0",
This should be dev dependency, right?

2022-10-19 21:19 UTC, gsanta commented on package.json
> +    "cypress": "^10.10.0",
Yes, I fixed it!

2022-10-22 06:15 UTC, Katona approved these changes

2022-10-22 06:15 UTC, merged